# from archlint import


class TestObjects:
    def test_function_strings(self): ...

    def test_method_strings(self): ...

    def test_strings(self): ...

    def test_methodless(self): ...

    def test_ignore_matching(self): ...

    def test_apply(self): ...


def test_collect_method_info(): ...


def test_parse_function(): ...


def test_collect_objects_in_md(): ...


def test_collect_docs_objects(): ...


def test_collect_object_texts(): ...


def test_collect_source_objects(): ...


def test_add_inherited_methods(): ...
