# from archlint import


def test_collect_objects_in_md(): ...


def test_collect_method_info(): ...


def test_collect_functions_in_text(): ...


def test_collect_classes_in_text(): ...


def test_collect_tests_objects(): ...


def test_collect_docs_objects(): ...


def test_collect_source_objects(): ...


def test_add_inherited_methods(): ...


class TestObjects:
    def test_function_strings(self): ...

    def test_method_strings(self): ...

    def test_methodless(self): ...

    def test_strings(self): ...

    def test_ignore_matching(self): ...

    def test_apply(self): ...

    def test_is_method(self): ...

    def test_fix_init(self): ...
