# from archlint.utils import under_any


# def test_under_any() -> None:
#     assert under_any(
#         Path("/tmp/hello-world/src/hello_world"),
#         re.compile(r"/[^/]*?hello[^/]*?/|/[^/]*?other/[^/]*?/"),
#     ) == Path("/tmp/hello-world")


def test_get_project_root(): ...
def test_walk_absolute_paths(): ...
def test_move_path(): ...
def test_relativize(): ...
def test_always_true(): ...
def test_assert_bool(): ...
def test_project(): ...
def test_sort_on_path(): ...
def test_deduplicate_ordered(): ...
def test_filter_with(): ...
def test_filter_without(): ...
def test_anywhere(): ...
def test_prepend_module_name(): ...
def test_dedup_underscores(): ...
def test_remove_body(): ...
def test_safe_search(): ...
def test_make_regex(): ...
def test_compile_for_path_segment(): ...
def test_compile_for_path_segment_or_bool(): ...
def test_get_method_name(): ...
def test_path_matches(): ...
def test_path_matches_not(): ...
def test_make_colorize_path(): ...
def test_make_double_bar(): ...
def test_make_bar(): ...
def test_make_half_bar(): ...
def test_indented(): ...


class TestColor:
    def test_no_color(self):
        # TODO
        ...

    def test_red(self):
        # TODO
        ...

    def test_green(self):
        # TODO
        ...

    def test_cyan(self):
        # TODO
        ...

    def test_black(self):
        # TODO
        ...

    def test_yellow(self):
        # TODO
        ...

    def test_blue(self):
        # TODO
        ...

    def test_magenta(self):
        # TODO
        ...

    def test_white(self):
        # TODO
        ...

    def test_colorize_path(self):
        # TODO
        ...
